### ISSUE TITLE
Fix install on Tripal 3 with legacy support enabled

### ISSUE THREAD

**Issue by guignonv** [tripal/brapi#6] opened 2019-01-10 18:12 UTC
The tripal_cv_load_obo_v1_2 function is not available.

**Comment by laceysanderson** [comment] 2019-01-10 19:31
The problem is due to the fact that the legacy obo loader was removed when the new one was created.

**Comment by laceysanderson** [comment] 2019-01-10 19:47
Fixed this by using the new obo loader when it is available and only reverting to the old obo loader when it's the only one.

**Comment by laceysanderson** [comment] 2019-01-10 21:28
Closing since PR fixing it has been merged

**Closed as completed by laceysanderson** 2019-01-10 21:28 UTC
Labels: bug
